authors = ["Guillaume KON KAM KING <guillaume.konkamking.work@gmail.com>"]
name = "DualOptimalFiltering"
version = "0.1.0"
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[deps]
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"

[compat]
julia = "[0.6.0,∞)"
